FROM ubuntu:22.04
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3-pip python3-setuptools python3-dev build-essential git openjdk-11-jdk wget unzip curl \
    libgl1-mesa-dev libgles2-mesa-dev libsqlite3-dev && \
    rm -rf /var/lib/apt/lists/*

RUN pip3 install --upgrade pip
RUN pip3 install buildozer cython

# Este Dockerfile es una base; recomendamos usar la imagen oficial 'kivy/buildozer'
WORKDIR /app

COPY . /app

CMD ["/bin/bash"]
